"""
Plan validation helpers.

Validates a semester plan (either generated by the solver or adjusted by the
user via drag-and-drop) for three constraint classes:

  1. Prerequisite order — a course cannot appear before one of its prereqs.
  2. Standing requirements — a course cannot appear before the student has
     accumulated enough units to meet its minimum standing level.
  3. Unit cap — a semester cannot exceed max_units_per_semester.

The validator operates on the serialized plan format (list-of-dicts) so it
can be called from both the API route and the test suite without importing
Pydantic models.
"""

from typing import Any, Optional  # Optional used by _highest_standing

from backend.engine.prereq_checker import detect_mutual_prereq_pairs
from backend.engine.solver import STANDING_UNITS


def validate_plan(
    semesters: list[dict[str, Any]],
    prerequisites: list[dict[str, Any]],
    max_units_per_semester: int = 15,
    completed_course_codes: Optional[list[str]] = None,
) -> list[dict[str, str]]:
    """
    Validate a plan and return a list of conflict dicts.

    Each conflict has keys:
      - course_code: the offending course (or "*" for semester-level issues)
      - reason: human-readable explanation

    Args:
        semesters: List of semester dicts, each with keys:
            "semester" (str), "year" (int), "courses" (list of course dicts),
            "total_units" (int).
        prerequisites: All prerequisite rows relevant to the plan's courses.
        max_units_per_semester: Unit cap (default 15, matching the API default).
        completed_course_codes: Courses the student completed before the plan.

    Returns:
        List of conflict dicts (empty = plan is valid).
    """
    completed: set[str] = set(completed_course_codes or [])
    cumulative_units: int = 0
    conflicts: list[dict[str, str]] = []

    # Build the full set of courses the plan knows about so we can skip
    # external prereqs (placement courses, old catalog numbers, etc.)
    plan_courses_set: set[str] = set(completed) | {
        c["course_code"]
        for sem in semesters
        for c in sem.get("courses", [])
    }

    # Detect mutual prereq pairs (A requires B AND B requires A) — co-requisite
    # cycles the solver intentionally co-places (e.g. PHYS 180A↔180B). Skip both
    # directions so the validator doesn't flag deliberate same-semester pairs.
    # Shared with prereq_checker so the two cannot drift.
    mutual_pairs = detect_mutual_prereq_pairs(prerequisites, plan_courses_set)

    for semester in semesters:
        sem_label = f"{semester.get('semester')} {semester.get('year')}"
        sem_type = (semester.get("semester") or "").strip().lower()
        courses: list[dict[str, Any]] = semester.get("courses", [])
        sem_units: int = sum(c.get("units", 0) for c in courses)

        # ── Offering term (fall-only / spring-only) ───────────────────────
        # The solver hard-filters courses by offered_fall / offered_spring,
        # but a manual drag can drop a fall-only course into a spring slot (or
        # vice-versa). Flag it so the user sees the same constraint the solver
        # enforces. Courses default to offered (placeholders are always both).
        for course in courses:
            if sem_type == "fall" and not course.get("offered_fall", True):
                conflicts.append({
                    "course_code": course["course_code"],
                    "reason": (
                        f"{course['course_code']} is not offered in the fall, "
                        f"but is placed in {sem_label}."
                    ),
                })
            elif sem_type == "spring" and not course.get("offered_spring", True):
                conflicts.append({
                    "course_code": course["course_code"],
                    "reason": (
                        f"{course['course_code']} is not offered in the spring, "
                        f"but is placed in {sem_label}."
                    ),
                })

        # ── Unit cap ──────────────────────────────────────────────────────
        # The cap is a soft TARGET (the Onboarding slider), not a hard rule — a
        # student may deliberately overload a semester. Surface it as a warning,
        # never a blocking conflict. (The solver still packs to the target during
        # generation; this only fires on user-driven drags.)
        #
        # Co-req labs get cap headroom (matching the solver): a lab taken in the
        # same semester as its lecture doesn't count against the target, so a
        # 1-unit lab never trips the over-cap warning just for staying with its
        # lecture. Excess over (cap + co-req-lab units) is still flagged.
        sem_codes_all = {c.get("course_code") for c in courses}
        lab_headroom = sum(
            c.get("units", 0) for c in courses
            if str(c.get("course_code", "")).endswith("L")
            and c["course_code"][:-1].rstrip() in sem_codes_all
        )
        if sem_units > max_units_per_semester + lab_headroom:
            conflicts.append({
                "course_code": "*",
                "reason": (
                    f"{sem_label} has {sem_units} units, above your "
                    f"{max_units_per_semester}-unit target."
                ),
                "severity": "warning",
            })

        # ── Per-course checks ─────────────────────────────────────────────
        sem_codes: set[str] = {c["course_code"] for c in courses}
        for course in courses:
            code = course["course_code"]
            prereq_rows = [
                row for row in prerequisites
                if row.get("course_code") == code
            ]

            # Prerequisites: check OR groups. Within each group, ANY ONE
            # member being completed satisfies the group. Skip external prereqs.
            prereq_groups = _build_validator_groups(prereq_rows, plan_courses_set, mutual_pairs)
            for group in prereq_groups:
                if not any(p in completed for p in group):
                    missing = sorted(group)
                    label = " or ".join(missing) if len(missing) > 1 else missing[0]

                    # Distinguish same-semester conflict from missing-entirely.
                    same_sem = [p for p in group if p in sem_codes]
                    if same_sem:
                        reason = (
                            f"Prerequisite {label} is in the same semester as "
                            f"{code} — it must be taken in a prior semester."
                        )
                    else:
                        reason = (
                            f"Prerequisite {label} is not completed "
                            f"before {sem_label}."
                        )
                    # `prereq_codes` is a structural key (the unmet group members)
                    # used to dedup against the transitive prereq-chain checker
                    # without depending on the wording of `reason`.
                    conflicts.append({"course_code": code, "reason": reason,
                                      "prereq_codes": missing})

            # Standing: check cumulative units before this semester.
            standing = _highest_standing(
                row.get("min_standing") for row in prereq_rows
            )
            if standing and cumulative_units < STANDING_UNITS[standing]:
                conflicts.append({
                    "course_code": code,
                    "reason": (
                        f"Requires {standing} standing "
                        f"({STANDING_UNITS[standing]}+ units before semester), "
                        f"but only {cumulative_units} units completed so far."
                    ),
                })

        # Courses taken this semester count toward standing in the next one.
        completed.update(c["course_code"] for c in courses)
        cumulative_units += sem_units

    return conflicts


def _build_validator_groups(
    prereq_rows: list[dict[str, Any]],
    plan_courses_set: set[str],
    mutual_pairs: Optional[set[tuple[str, str]]] = None,
) -> list[set[str]]:
    """
    Group prerequisite rows into OR sets for validation.

    Mirrors the solver's _build_prereq_groups but without removed_edges
    (the validator checks the plan as-is, not during construction).
    Rows with the same prereq_group value are OR alternatives.
    Rows without a group are standalone AND requirements.
    Only includes prereqs that are in the plan's known course set.
    """
    from collections import defaultdict
    standalone: list[set[str]] = []
    grouped: dict[Any, set[str]] = defaultdict(set)

    for row in prereq_rows:
        prereq_code = row.get("prereq_code")
        if not prereq_code:
            continue
        if row.get("prereq_type") != "required":
            continue
        if prereq_code not in plan_courses_set:
            continue
        # Skip the backwards lab→lecture direction that the scraper captures as
        # a cycle (e.g. CS 150 listing CS 150L as prereq). The solver orders
        # lecture before lab; the reverse row is a data artifact.
        course_code_val = row.get("course_code", "")
        if prereq_code.endswith("L") and prereq_code[:-1].rstrip() == course_code_val:
            continue
        # A lab's own lecture is a CO-REQUISITE (same semester is correct), not a
        # strict-earlier prereq — don't flag the lab for sharing the lecture's term.
        if course_code_val.endswith("L") and course_code_val[:-1].rstrip() == prereq_code:
            continue
        # Skip mutual co-requisite pairs the solver co-places intentionally.
        if mutual_pairs and (course_code_val, prereq_code) in mutual_pairs:
            continue
        group_id = row.get("prereq_group")
        if group_id is None:
            standalone.append({prereq_code})
        else:
            grouped[group_id].add(prereq_code)

    return standalone + [s for s in grouped.values()]


def _highest_standing(levels) -> Optional[str]:
    """Return the most restrictive standing level from an iterable."""
    valid = [lvl for lvl in levels if lvl and lvl in STANDING_UNITS]
    if not valid:
        return None
    return max(valid, key=lambda lvl: STANDING_UNITS[lvl])
